- app/controllers/candidate.js
- app/controllers/offices.js
- app/controllers/parties.js
- app/controllers/users.js
- app/controllers/votes.js
- app/helpers/auth.js
- app/helpers/seed.js
- app/middleware/auth.js
- app/models/dbModel.js
- app/route.js
- app/seed/candidates.js
- app/seed/offices.js
- app/seed/parties.js
- app/seed/petitions.js
- app/seed/users.js
- app/seed/votes.js
- app/server.js
> feat(endpoints): create vote endpoints

- UI/CSS/background.css
- UI/CSS/layout.css
- UI/JS/admin.js
- UI/admin.html
- UI/candidate.html
- UI/home.html
- UI/profile.html
Add functionality to UI pages
Add cursor pointer functionality to links
add footer
https://basilcea.github.io/politico/UI/
n/a
n/a
n/a
> fix(bug-fix):gh pages

- UI/JS/vote.js
Host user front end online
n/a
https://basilcea.github.io/politico/UI/
n/a
n/a
n/a
n/a
> feat(UI): Host UI

- app/controllers/candidate.js
- app/controllers/offices.js
- app/controllers/parties.js
- app/controllers/petition.js
- app/controllers/users.js
- app/controllers/votes.js
- app/helpers/auth.js
- app/helpers/schema.js
- app/models/dbModel.js
- app/route.js
- app/seed/interests.js
- package-lock.json
- package.json
Add make petitions endpoint to develop
Create petitions endpoints
method  POST
route localhost:3000/api/v1/petitions
n/a
https://www.pivotaltracker.com/story/show/163552241
n/a
n/a
> #163552241 create petitions endpionts

- app/controllers/parties.js
- app/controllers/petition.js
- app/helpers/mailer.js
- app/helpers/schema.js
- app/route.js
Add edit petitions endpoint to develop
Edit petitions endpoints
checkout to ft-edit-petition-164134702
method  POST
route localhost:3000/api/v1/petitions
n/a
https://www.pivotaltracker.com/story/show/164134702
n/a
n/a
> #164134702 edit petitions

- app/controllers/petition.js
- app/route.js
call get users petitions endpoint 
Check if user created a petition
Get user petitions
method  GET
route localhost:3000/api/v1/petitions
n/a
https://www.pivotaltracker.com/story/show/164137104
n/a
n/a
> #164137104  create get user petition endpoint

- app/controllers/petition.js
- app/route.js
Get a single user petition 
Check if user created a petition
Get a single petition
method  GET
route localhost:3000/api/v1/petitions/3
n/a
https://www.pivotaltracker.com/story/show/164138437
n/a
n/a
> #164138437 Get a single user petition

- app/controllers/petition.js
- app/route.js
Delete a Petition Made
Admin can delete any petition
User can delete a petition created by user only
method  GET
route localhost:3000/api/v1/petitions/3
n/a
https://www.pivotaltracker.com/story/show/164139188
n/a
n/a
>  #164139188 create endpoints to delete petitions

- app/controllers/interest.js
- app/controllers/petition.js
- app/helpers/schema.js
- app/route.js
- Refactor joi validation
- User must have politician status to express interest
[Finishes #164143499]
> #164143499  Create endpiont for expressing interest

- app/controllers/interest.js
- app/controllers/petition.js
- app/helpers/schema.js
- app/route.js
-Refactor joi validation
-Refactor get petition
[Finishes #164157477]
> #164157477 create edit interest endpoints

- app/controllers/interest.js
- app/route.js
- User should get all interests expressed by user alone
- Admin should get all interests by all users
-[Finishes #164158440]
> #164158440  get all political interests

- app/controllers/interest.js
- app/route.js
-Only user can delete interest
[Finishes #164158799]
> #164158799 create endpoint to delete user interest

- app/controllers/candidate.js
- app/route.js
> #164159117 create  search candidate endpoint

- app/controllers/candidate.js
- app/controllers/interest.js
- app/route.js
- Only admin can edit candidate
[Finishes #164161165]
> #164161165 create endpoints to edit candidates

- app/controllers/candidate.js
- app/controllers/offices.js
- app/controllers/parties.js
- app/controllers/petition.js
- app/route.js
- Only admin can delete candidate
[Finishes #164161823]
> #164161823 create endpoint to delete candidate

- app/controllers/users.js
- app/helpers/schema.js
- app/route.js
- Admin cannot be a politician
- A Candidate cannot edit registerAs status
- interest deleted on change of status from politician to voter
[Finishes #164163036]
> #164163036 creae edit profile endpoints

- app/controllers/users.js
- app/helpers/schema.js
- app/route.js
> #16167063 create change password endpoint

- app/controllers/users.js
- app/route.js
- User can only delete own profile
[Finishes #164169459]
> #164169459 create endpoint for deleting profile

- app/controllers/offices.js
- app/controllers/users.js
- app/controllers/votes.js
- app/helpers/schema.js
- app/models/dbModel.js
- app/route.js
- Only admin can edit office
[Finishes #164171791]
> #164171791 create endpionts for editing office

- app/controllers/offices.js
- app/controllers/parties.js
- app/route.js
> #164180436 create endpoint to delete office

- app/controllers/users.js
- app/route.js
- Only admin cam make user admin
[Finishes #164185452]
> #164185452 create makeAdmin endpoints

- .travis.yml
- write test for signup endpoint
- implement fetch for user endpoints
[Finishes #164190514]
> #164190514 fetch user signup

- app/migrate.js
- package.json
- set SSL to true for production environment
- set SSL false for other environment
[Fixes #164190514]
> #164190514 Resolve environment variables

- UI/JS/index.js
- UI/index.html
- app/middleware/validate.js
- fetch user login endpoint
- Authenticate for already signup user
[Finishes #164351040]
> #164351040 build login from front end

- UI/CSS/form.css
- UI/JS/index.js
- UI/index.html
- app/controllers/users.js
- app/helpers/schema.js
- test/userSpec.js
-Validate that user exists
-check if connection exists
[Finishes #164351356]
> #164351356 create reset password functionality from frontend

- app/controllers/activity.js
- app/controllers/users.js
- app/route.js
- test/userSpec.js
- get user profile if user is logged in
[Finishes #164461096]
> feat(endpoints): user should be able to  view profile

- UI/JS/uploadPix.js
- app/controllers/activity.js
- app/helpers/schema.js
- app/middleware/validate.js
- app/route.js
- create new schema for editProfile
- update valida.js with editProfile schema
- remove previous validation from userActivity controller
> #164430614  fix validation error for editProfile

- app/controllers/activity.js
> #164430614 fix develop bug

- app/controllers/activity.js
- app/helpers/schema.js
- change fom to from in sql syntax
-update edit profile validation schema
> #164430614 fix edit profile bugs

- package.json
- Run migrate createAllTables on Heroku
> #164420614 add make-runnable as a dependency

- UI/JS/home.js
- UI/JS/index.js
- UI/JS/profile.js
- UI/JS/uploadPix.js
- UI/index.html
- UI/profile.html
-Status change should affect a user who is an admin#
- Status change affectsa user who is a politicia
[Finishes #164472742]
> #164472742  Fetch edit profile

- app/route.js
> #164430614 Fix change password http method

- UI/JS/home.js
- UI/JS/index.js
- UI/JS/profile.js
- UI/home.html
- UI/profile.html
- Reset password on succesful change
[Finishes #164495501]
> #164495501 fetch change password 

- UI/CSS/form.css
- UI/JS/index.js
- UI/JS/profile.js
- UI/profile.html
-User should type first name to verify delete action
- User should check buton to delete action
[Finishes #164501802]
> #164501802 fetch delete profile endpoint

- app/controllers/users.js
> #164430614 make first user admin

- app/controllers/users.js
- app/helpers/auth.js
- app/middleware/auth.js
- app/route.js
> #164430614  Edit number of variables for generating token

- UI/JS/decrypt.js
- app/helpers/schema.js
- app/middleware/validate.js
- app/route.js
- add create party validation schema
> #164430614 Fix invalid value submission

- app/controllers/parties.js
-Remove validation in controllers
- Use Validation middleware
> #164430614 fix create party bug

- UI/CSS/fadeIn.css
- UI/CSS/nav.css
- UI/CSS/others.css
- UI/JS/admin.js
- UI/JS/decrypt.js
- UI/JS/home.js
- UI/JS/index.js
- UI/JS/logout.js
- UI/JS/profile.js
- UI/admin.html
- UI/home.html
- UI/index.html
- UI/profile.html
> #164518077 Fetch create party endpoint

- app/controllers/parties.js
- app/helpers/schema.js
- app/middleware/validate.js
- app/route.js
> #164430614 Refactor edit party endpoint

- app/middleware/validate.js
- change req.body to req.params.id
> #164430614 fix validation error for parameter id

- UI/JS/admin.js
- UI/JS/getParties.js
- UI/JS/home.js
- UI/JS/uploadPix.js
- UI/admin.html
- get all parties and load into select option
- Make value of each option the party id
- select a party
- fetch a single party
- edit a party
[Finishes #164538384]
> #164538384 Edit user party from front end

- UI/JS/admin.js
- UI/JS/data.js
- UI/JS/getParties.js
- UI/admin.html
> #164562900 fetch delete party endpoint

- app/helpers/schema.js
- app/models/dbModel.js
- app/route.js
- app/seed/parties.js
- Refactor validation errors
[Fixes 164430614]
> #164430614 fix validation for office endpoints

- app/middleware/validate.js
- app/route.js
> #164430614 fix validation error

- app/controllers/offices.js
- app/helpers/schema.js
> #164430614 fix office electDate validation error

- app/controllers/offices.js
- add third placeholder for sendoffice values
> #164430614 fix error with create office

- app/controllers/activity.js
- app/controllers/offices.js
- app/controllers/users.js
> #164430614 fix delete office endpoint validation error

- UI/JS/admin.js
- UI/JS/decrypt.js
- UI/JS/getOffices.js
- UI/JS/getParties.js
- UI/JS/home.js
- UI/JS/index.js
- UI/JS/profile.js
- UI/JS/uploadPix.js
- UI/admin.html
- UI/home.html
- UI/index.html
- UI/profile.html
- fetch create office endpoints
- fetch edit office endpoints
- fetch delete office endpoints
[Finishes #164563743]
> #164563743 fetch office endpoints from frontend

- app/controllers/activity.js
- fix makeAdmin endpoint
- fix edit profile endpoint
> #164430614 fix response data in activity endpoints

- app/controllers/votes.js
- app/route.js
>  #164602666 Get all user votes

- app/route.js
> #164602666 Build get all user votes endpoint

- app/controllers/interest.js
- app/helpers/schema.js
- app/middleware/validate.js
- app/route.js
- Make edit endpoint accessable to admin
- create validation schema for interest endpoints
- add validation as middleware to interest routes
> #164430614 fix validation errors for interest endpoints

- app/controllers/interest.js
> #164430614 remove admin can edit interests

- app/controllers/interest.js
- admin can get all interests
- Admin cannot edit an interest
[Fixes 164430614]
> #164430614 fix edit interest endpoint

- app/controllers/candidate.js
- app/controllers/petition.js
- app/helpers/schema.js
- app/middleware/validate.js
- app/route.js
add validation middleware to route
> #164430614 Add validation for unvalidated endpoints

- app/controllers/candidate.js
- app/controllers/interest.js
- app/route.js
- Add user can only express interest for an office once
- Admin can get all candidates
[Finishes #164679181]
> #164679181 create get all candidates endpoints

- app/controllers/candidate.js
- app/route.js
> #164430614 Fix get a candidate endpoint

- app/controllers/candidate.js
> #164430614 fix query value in get candidate endpiont

- UI/JS/getInterests.js
- fetch get a candidate endpoint
- fetch delete a candidate endpoint
- fetch create a candidate endpoint
[Finishes #164658545]
> #164658545 fetch candidates endpoints

- app/controllers/candidate.js
- response should include candidate name and passport
- response should include party name and logo
> #164430614 fix response data for search candidate endpoint

- app/controllers/candidate.js
- app/controllers/interest.js
…oint
- Refactor search candidate endpoint
- Refactor get interest endpoint
> #164430614 fix search candidate endpoint

- app/controllers/interest.js
> #164430614 fix get interest endpoint

- app/controllers/interest.js
> #164430614 add passport url to get interest endpoint

- app/controllers/candidate.js
> #164430614 edit get candidate endpionts

- app/controllers/candidate.js
> f#164430614 edit getcandidateById endpoints

- app/route.js
> #164430614 edit route

- app/controllers/candidate.js
- app/route.js
> #164430614 fix validation error with get candidate endpoint#

- app/controllers/candidate.js
> #164430614 fix id not defined in get candidate

- app/controllers/candidate.js
> #164430614 fix error with getCandidate by id

- UI/JS/getPetitions.js
- app/controllers/petition.js
> #164430614 fix validation error in create petition schema

- UI/JS/candidate.js
- UI/JS/decrypt.js
- UI/JS/getInterests.js
- UI/JS/getPetitions.js
- UI/JS/profile.js
- UI/JS/uploadPix.js
- UI/candidate.html
fetch create petition
fetch view petition
fetch delete petition
fetch edit petition
[Finishes #164712715]
> #164712715 fetch petitions endpionts
